 SELECT o.id AS order_id,
    o.order_number,
    o.status,
    o.total,
    o.created_at,
    o.due_date,
    o.trashed_at,
    o.client_id,
    o.client_name,
    o.created_by,
    o.picker_id,
    o.volume_count,
    o.label_print_count,
    o.tenant_id,
    oi.id AS item_id,
    oi.material_id,
    oi.quantity,
    oi.conditions,
    oi.unit_price,
    oi.color,
    oi.shortage_action,
    oi.qty_reserved_from_stock,
    oi.qty_to_produce,
    oi.qty_separated,
    oi.separated_weight,
    oi.item_condition,
    oi.condition_template_name,
    m.name AS material_name,
    m.unit AS material_unit
   FROM orders o
     LEFT JOIN order_items oi ON oi.order_id = o.id
     LEFT JOIN materials m ON m.id = oi.material_id;